package com.project.code.Model;

import jakarta.validation.constraints.NotNull;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Document(collation = "reviews")
public class Review {

    private String comment;

    @NotNull(message = "Customer cannot be null")
    private Long customerId;

    @Id
    private String id;

    @NotNull(message = "Product cannot be null")
    private Long productId;

    @NotNull(message = "Rating cannot be null")
    private Integer rating;

    @NotNull(message = "Store cannot be null")
    private Long storeId;

    public Review(String comment, Long customerId, Long productId, Integer rating, Long storeId) {
        this.comment = comment;
        this.customerId = customerId;
        this.productId = productId;
        this.rating = rating;
        this.storeId = storeId;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public @NotNull(message = "Customer cannot be null") Long getCustomerId() {
        return customerId;
    }

    public void setCustomerId(@NotNull(message = "Customer cannot be null") Long customerId) {
        this.customerId = customerId;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public @NotNull(message = "Product cannot be null") Long getProductId() {
        return productId;
    }

    public void setProductId(@NotNull(message = "Product cannot be null") Long productId) {
        this.productId = productId;
    }

    public @NotNull(message = "Rating cannot be null") Integer getRating() {
        return rating;
    }

    public void setRating(@NotNull(message = "Rating cannot be null") Integer rating) {
        this.rating = rating;
    }

    public @NotNull(message = "Store cannot be null") Long getStoreId() {
        return storeId;
    }

    public void setStoreId(@NotNull(message = "Store cannot be null") Long storeId) {
        this.storeId = storeId;
    }
// 1. Add 'customerId' field:
//    - Type: private Long
//    - This field represents the customer who created the review.
//    - This field cannot be empty, use the @NotNull annotation to enforce this rule.

// 2. Add 'productId' field:
//    - Type: private Long
//    - This field represents the product being reviewed.
//    - This field cannot be empty, use the @NotNull annotation to enforce this rule.

// 3. Add 'storeId' field:
//    - Type: private Long
//    - This field represents the store associated with the product.
//    - This field cannot be empty, use the @NotNull annotation to enforce this rule.

// 4. Add 'rating' field:
//    - Type: private Integer
//    - This field represents the rating given to the product (out of 5).
//    - This field cannot be empty, use the @NotNull annotation to enforce this rule.

// 5. Add 'comment' field:
//    - Type: private String
//    - This field represents an optional comment on the product.

// 6. Add validation:
//    - Apply @NotNull to the customerId, productId, storeId, and rating fields to ensure they are not null.
//    - Example: @NotNull(message = "Customer cannot be null")

// 7. Add @Document annotation:
//    - Use @Document(collection = "reviews") to indicate that this class represents a MongoDB document.

// 8. Add constructor:
//    - The constructor should accept values for customerId, productId, storeId, rating, and an optional comment.

// 9. Add @Id annotation:
//    - Use @Id to mark the field 'id' as the primary key for MongoDB.
//    - The 'id' field is of type String and will be automatically generated by MongoDB.

// 10. Add Getters and Setters:
//    - Add getter and setter methods for all fields (customerId, productId, storeId, rating, comment).


}
